language: cpp

compiler:
  - gcc

before_script:
  - mkdir build
  - cd build
  - cmake -DINSTDIR:STRING=~/services -DDEFUMASK:STRING=077 -DCMAKE_BUILD_TYPE:STRING=DEBUG -DUSE_RUN_CC_PL:BOOLEAN=ON ..

script:
  - make

notifications:
  webhooks: http://n.tkte.ch/h/4709/ij_epBokkneRq6moA-8hzsXx
